[package]
name = "aoc_2021_rust"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.46.1"
indexmap = "2.1.0"
itertools = "0.12.0"
regex = "1.10.2"
